# Temporary GitPage Host setup
title: CS230 Deep Learning
baseurl: "/cs230-2019-fall"
repository: "haossr/cs230-2019-fall"

# Theme settings
doks:
    color_theme: blue
    header:
        logo:
            text: CS230
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Project
              item_url: '/project'
            - item_name: Section
              item_url: '/section'
            - item_name: Lecture
              item_url: '/lecture'
            - item_name: Blog
              item_url: '/blog'
            - item_name: FAQ
              item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2019. - Stanford University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course:
    quarter: 2020 Winter
    time: Tue 9:00 AM - 10:20 AM
    venue: NVIDIA Auditorium
    piazza: &pz 'https://piazza.com/class/k533d6ufdfg5dv'
    queuestatus:
        url: &qs 'https://queuestatus.com/queues/515'
        name: 'CS230 (2020 Winter)'
    canvas: ''
    midterm_time: 02/19 Wednesday 6-9 PM
    project_timeline:
        proposal: 2020-01-22T23:59:00-07:00
        milestone: TBD (around Week 7)
        poster_and_report: 2020-03-15T23:59:00-08:00
        poster_session: 03/18 Wednesday 8:30 AM - 11:30 AM
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon:
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-sponsoring:
            content: Sponsoring a Project
            url: 'https://docs.google.com/forms/d/e/1FAIpQLSfJOXvQq46sfie8Z6e8Tp8v0_3khker3wrJJR44VyTINcGLiA/viewform'
            external_url: true
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        video2018:
            icon:
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false
        piazza:
            icon:
            content: Piazza
            url: *pz
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/112249/external_tools/3367'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: true
    staff:
        - name: Andrew Ng
          type: Instructor
          url: https://www.andrewng.org/
          image: andrew.jpg
        - name: Kian Katanforoosh
          type: Instructor
          url: https://www.linkedin.com/in/kiankatan/
          image: kian.jpg
        - name: Swati Dube
          type: Coordinator
          url: http://www.linkedin.com/in/swatidube/
          image: swati.jpg
        - name: Jon Braatz
          type: Head TA
          url:
          image: jon.jpg
          zoom_id: 5026279572
          calendly: https://calendly.com/cs230winter2020/jon-oh
    ta:
        - name: Jo Chuang
          type: On-campus TA
          url: https://jochuang.com/
          image: jo.jpg
          zoom_id: 8543765436
          calendly: https://calendly.com/cs230winter2020/jo-oh
        - name: Vineet Kosaraju
          type: On-campus TA
          url: https://vineetkosaraju.com/
          image: vineet.png
          zoom_id: 2698484179
          calendly: https://calendly.com/cs230winter2020/vineet-oh
        - name: Shahab Mousavi
          type: On-campus TA
          url: https://www.linkedin.com/in/shahab-mousavi-39394738/
          image: shahab.jpg
          zoom_id: 9392472642
          calendly: https://calendly.com/cs230winter2020/shahab-oh
        - name: Advay Pal
          type: On-campus TA
          url: https://advaypal.com/
          image: advay.jpg
          zoom_id: 5123418143
          calendly: https://calendly.com/cs230winter2020/advay-oh
        - name: Pranav Rajpurkar
          type: On-campus TA
          url: https://rajpurkar.github.io/
          image: pranav.jpg
          zoom_id: 7586009555
          calendly: https://calendly.com/cs230winter2/pranav-oh
        - name: Sherry Ruan
          type: On-campus TA
          url: https://www.linkedin.com/in/sherrysruan
          image: sherry.jpg
          zoom_id: 3672079800
          calendly: https://calendly.com/cs230winter2020/sherry-oh
        - name: Chris Waites
          type: On-campus TA
          url: https://chriswaites.com/
          image: chris.jpg
          zoom_id: 7534542794
          calendly: https://calendly.com/cs230winter2020/chris-oh
        - name: Jingbo Yang
          type: On-campus TA
          url: https://www.linkedin.com/in/jingbo-eric-yang-36b0b08a/
          image: jingbo.jpg
          zoom_id: 3380771726
          calendly: https://calendly.com/cs230winter2/jingbo-oh
        - name: Leo Mehr
          type: On-campus TA
          url: https://leomehr.com/
          image: leo.png
          zoom_id: 5470200840
          calendly: https://calendly.com/cs230winter2020/leo-oh
