# Temporary GitPage Host setup
title: Deep Learning
baseurl: "/deep-learning"

# Theme settings
doks:
    color_theme: blue
    header:
        logo:
            text: Deep Learning
            image: false
        nav:
            - item_name: Lectures
              item_url: '/lectures'
            - item_name: Blogs
              item_url: '/blogs'
            - item_name: Sections
              item_url: '/sections'              
            - item_name: Papers
              item_url: '/papers'
            - item_name: Projects
              item_url: '/projects'
            - item_name: Notes
              item_url: '/notes'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2020. - Pedro Abundio Wang <br>All rights reserved.
        social_list:
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course:
    links:
        papers:
            icon:
            content: Papers
            url: '/papers'
            external_url: false
        projects:
            icon:
            content: Projects
            url: '/projects'
            external_url: false
        sections:
            icon:
            content: Sections
            url: '/sections'
            external_url: false
        lectures:
            icon:
            content: Lectures
            url: '/lectures'
            external_url: false
        blogs:
            icon:
            content: Blogs
            url: '/blogs'
            external_url: false
        notes:
            icon:
            content: Notes
            url: '/notes'
            external_url: false
